FROM apache/airflow:2.9.3-python3.11
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless procps && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.8.1 \
    hdfs==2.7.3 requests==2.32.3 kafka-python==2.0.2 PyYAML==6.0.2
ENV PYTHONPATH=/opt/datalake/src \
    DATALAKE_CONF=/opt/datalake/conf/sources.yml
